# Generated by Django 3.0.4 on 2020-03-30 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='corona_app.State'),
        ),
        migrations.AddField(
            model_name='state',
            name='death',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='patients',
            field=models.IntegerField(default=0),
        ),
    ]
