# Generated by Django 3.0.4 on 2020-03-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0002_auto_20200330_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='death',
        ),
        migrations.RemoveField(
            model_name='state',
            name='recovered',
        ),
        migrations.AddField(
            model_name='country',
            name='death',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='recovered',
            field=models.IntegerField(default=0),
        ),
    ]
