# Generated by Django 3.0.4 on 2020-04-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0003_auto_20200331_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='active_now',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='patients',
            field=models.IntegerField(default=0),
        ),
    ]
