# Generated by Django 3.0.4 on 2020-04-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0007_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.AddField(
            model_name='about',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
