# Generated by Django 3.0.4 on 2020-04-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0008_auto_20200402_1444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
