# Generated by Django 3.0.4 on 2020-04-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0010_auto_20200407_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='active_now',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='death',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='recovered',
            field=models.IntegerField(default=0),
        ),
    ]
