# Generated by Django 3.0.4 on 2020-04-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0011_auto_20200412_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='delta_confirmed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='delta_death',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='delta_recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='delta_confirmed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='delta_death',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='delta_recovered',
            field=models.IntegerField(default=0),
        ),
    ]
