# Generated by Django 3.0.4 on 2020-04-16 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0012_auto_20200414_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
