# Generated by Django 3.0.5 on 2020-04-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0013_country_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='last_updated',
        ),
    ]
