# Generated by Django 3.0.5 on 2020-04-19 16:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0014_remove_country_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date_str', models.CharField(max_length=50, unique=True)),
                ('total_confirmed', models.IntegerField()),
                ('total_recovered', models.IntegerField()),
                ('total_death', models.IntegerField()),
                ('delta_confirmed', models.IntegerField()),
                ('delta_recovered', models.IntegerField()),
                ('delta_death', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
