# Generated by Django 3.0.5 on 2020-07-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_app', '0015_casetimeseries'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='casetimeseries',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='active_now',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='death',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='delta_confirmed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='delta_death',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='delta_recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='district',
            name='recovered',
            field=models.IntegerField(default=0),
        ),
    ]
